### ISSUE TITLE
SDL 2 joysticks are working with the game? 

### ISSUE THREAD

**Issue by xcom169** [lemon-sherbet/ccleste#2]
Hello!
SDL 2 joysticks eg. DS4 gamepad, are working with the game?

**Comment by lemon32767** [comment]
Hi,
Currently, not. But I'll add it, give me some time.

**Comment by lemon32767** [comment]
implemented in https://github.com/lemon-sherbet/ccleste/commit/81e9161bbb9382308d6b8af5045598f056023642

**Comment by xcom169** [comment]
Thank you very much!
