### ISSUE TITLE
Not an issue, just some notes

### ISSUE THREAD

**Issue by theofficialgman** [lemon-sherbet/ccleste#4]
Loving this port but there are a few things that I would like added to your master ccleste repo
I've already hacked them together in my fork https://github.com/theofficialgman/ccleste/tree/upstream_edits but the changes are hacks and not proper implementations

the issue with moving to sdl2 is that now the fullscreen mode places the window in the top left corner of the screen and leftover image data is drawn around the gameplay. this wasn't the case with the sdl1.2 fullscreen which centered the window and did not draw the out of bounds rendering

The gamecontroller api fails to function if the controller which is used does not have a mapping the the global gamecontroller.db file, better to allow the user to load their own

saves/load and exit can't be executed from a controller

all of these have been hacked in through my upstream_edits branch of my fork. they are hacks because they do not care for sdl1.2 compatibility so if/else statements may be needed to ensure compatibility with both versions

**Comment by theofficialgman** [comment]
oh, I also have scaling function within my fork as well in both sdl1.2 and sdl2 version (master is my old sdl1.2 only fork before you added the new changes, and upstream_edits is my new fork for sdl2)

**Comment by rien333** [comment]
Any change you could transform these "hacks" into pull requests? (that would be less complex to handle for my package manager) See also  my issue #7.

**Comment by theofficialgman** [comment]
@rien333 the changes are now in master as of February
I forgot to close this issues. closing now
