### ISSUE TITLE
Ability to remap buttons

### ISSUE THREAD

**Issue by rien333** [lemon-sherbet/ccleste#8]
Preferably, the user should be able to remap the buttons as she wants via some sort of config file. (I know I can just simply recompile with my preferences, but this a bit more hassle in terms of package management). For instance, the game now uses a different button than celeste (the main game)  for jumping (on my PS3 controller on Linux).

**Comment by lemon32767** [comment]
Implemented controller button remapping https://github.com/lemon32767/ccleste/commit/1af40b781684f4fcc7bab2ced73ef76672e3d7a4
